programmet: huvudfil.cpp addContact.cpp addContact.h search.cpp search.h remove.cpp remove.h
	g++ -o programmet huvudfil.cpp addContact.cpp  search.cpp remove.cpp

run: programmet
	./programmet

clean:
	rm programmet
